[package]
name = "bread-manager"
version = "0.1.0"
edition = "2021"
description = "deesc"

authors = ["Thomas Ellmenreich <thomas.ellmenreich@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.34", features = ["serde"] }
eframe = "0.26.2"
egui = "0.26.2"
egui_dock = "0.11.1"
egui_extras = "0.26.2"
env_logger = "0.11.2"
flowync = "5.1.0"
futures = "0.3.30"
lazy_async_promise = "0.5.0"
pollster = "0.3.0"
rayon = "1.8.1"
rfd = "0.13.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio", "uuid"] }
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "v7", "serde"] }

