[package]
name = "bread-manager"
version = "0.1.0"
edition = "2021"
description = "deesc"

authors = ["Thomas Ellmenreich <thomas.ellmenreich@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.38", features = ["serde"] }
eframe = "0.28.1"
egui = "0.28.1"
egui_dock = "0.13.0"
egui_extras = "0.28.1"
egui_plot = "0.28.1"
env_logger = "0.11.5"
flowync = "5.1.0"
futures = "0.3.30"
lazy_async_promise = { path = "../lazy_async_promise" } # "0.5.0"
pollster = "0.3.0"
rayon = "1.10.0"
rfd = "0.15.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio", "uuid", "chrono"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4", "v7", "serde"] }
egui_light_states = { path = "../egui_light_states" }
data_communicator = { path = "../data_communicator" }

