//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

use crate::model::{
    group::GroupUuid,
    transactions::{datetime::DatetimeUuid, properties::OriginType},
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "datetime")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: DatetimeUuid,
    pub origin_type: OriginType,
    #[sea_orm(column_type = "custom(\"DATE\")")]
    pub date: String,
    #[sea_orm(column_type = "custom(\"TIME\")", nullable)]
    pub time: Option<String>,
    pub timezone: i32,
    pub group_uuid: GroupUuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::data_groups::Entity",
        from = "Column::GroupUuid",
        to = "super::data_groups::Column::Uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    DataGroups,
    #[sea_orm(has_many = "super::data_import_row_item::Entity")]
    DataImportRowItem,
    #[sea_orm(has_many = "super::transaction_datetime::Entity")]
    TransactionDatetime,
}

impl Related<super::data_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataGroups.def()
    }
}

impl Related<super::data_import_row_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataImportRowItem.def()
    }
}

impl Related<super::transaction_datetime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionDatetime.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        super::transaction_datetime::Relation::Transaction.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::transaction_datetime::Relation::Datetime.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
