//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "possible_transaction_link_create_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub datetime_created: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::possible_transaction_link::Entity")]
    PossibleTransactionLink,
}

impl Related<super::possible_transaction_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PossibleTransactionLink.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
