//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profile_content_descriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub content_uuid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_uuid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::content_description::Entity",
        from = "Column::ContentUuid",
        to = "super::content_description::Column::Uuid",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ContentDescription,
    #[sea_orm(
        belongs_to = "super::profile::Entity",
        from = "Column::ProfileUuid",
        to = "super::profile::Column::Uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Profile,
}

impl Related<super::content_description::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentDescription.def()
    }
}

impl Related<super::profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
