//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

use crate::model::transactions::{
    datetime::DatetimeUuid, properties::TransactionRelType, TransactionUuid,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transaction_datetime")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub transaction_uuid: TransactionUuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub datetime_uuid: DatetimeUuid,
    pub rel_type: TransactionRelType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::datetime::Entity",
        from = "Column::DatetimeUuid",
        to = "super::datetime::Column::Uuid",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Datetime,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::TransactionUuid",
        to = "super::transaction::Column::Uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Transaction,
}

impl Related<super::datetime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Datetime.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
