name: Cargo Fmt, Check and Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  fmt-check:
    name: Rust project - latest
    runs-on: rustdocker/rust:nightly
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check
      - run: cargo clippy -- -D clippy::pedantic

  audit:
    name: Audit rust project
    runs-on: rustdocker/rust:nightly
    steps:
      - uses: actions/checkout@v3
      - run: cargo audit

  test:
    name: Audit rust project
    runs-on: rustdocker/rust:nightly
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose
  

